name: creatare
favicon: null
layout_spectrum: 0.16364515176974237
typography_spectrum: 0.2101876805536449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.565376637969166
  lightness: 0.03997896355576813
  saturation: 0.6761405954603106
  rhythmicContrast: 0.9748741735238582
purpose: []
